# SPDX-FileCopyrightText: 2022 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
#
# SPDX-License-Identifier: MIT

name: Translations Sync

on:
  workflow_call:
    secrets:
      TX_TOKEN:
        required: true
      CI_SSH_KEY:
        required: true

jobs:
  update-translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update translations
        uses: liri-infra/translation-action@master
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
        with:
          ssh_key: ${{ secrets.CI_SSH_KEY }}
          committer_name: Liri CI
          committer_email: ci@liri.io
          translations_folder: translations
